account_id = "014848309742"
api_administrator_user_name = "APIAdministrator"
console_administrator_user_name = "Administrator"
user_name = "mockserver-pipeline-user"
lock_table_name = "mockserver-terraform-state-lock-dynamo"
state_bucket_name = "mockserver-terraform-remote-state-storage"
credential_encryption_user_arn = "arn:aws:iam::014848309742:user/APIAdministrator"